name: Publish (pypi)

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install uv
        run: |
          pip install -r requirements.setup.txt
      - name: Build distributions
        run: |
          uv build
      - name: Upload distributions
        uses: actions/upload-artifact@v7
        with:
          name: release-distributions
          path: dist/

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/sqlfluff-complexity
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash
    env:
      PYTHON_PACKAGE_NAME: sqlfluff-complexity
      PYTHON_NAME_SPACE: sqlfluff_complexity
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v8
        with:
          name: release-distributions
          path: dist/
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.13.0

  test-published-package:
    needs:
      - publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    env:
      PYTHON_PACKAGE_NAME: sqlfluff-complexity
      PYTHON_NAME_SPACE: sqlfluff_complexity
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python-version }}"
      # It takes some time when the package gets available.
      - name: Sleep
        run: |
          sleep 30
      - name: Install package
        run: |
          python3 -m pip install -U "${{ env.PYTHON_PACKAGE_NAME}}"
      - name: Test package
        run: |
          python3 -m "${{ env.PYTHON_NAME_SPACE }}"
